# Generated by Django 4.1.3 on 2023-01-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_person_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
